ci:
  skip: [pytest]

default_language_version:
  python: python3.12

repos:
  # general checks (see here: https://pre-commit.com/hooks.html)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # black - formatting
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        name: black
        args:
          - "--config"
          - "./pyproject.toml"

  # ruff - linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.3.0"
    hooks:
      - id: ruff
        name: ruff

  # mypy - lint-like type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: mypy

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest --cov=src tests
        language: system
        types: [python]
        pass_filenames: false