name: Python build, test, type-check

on:
  push:
    branches:
      - feat/modernization  
  pull_request:
    branches:
      - main 

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'
  
    - name: Install poetry
      run: |
        python -m pip install poetry==1.1.11
        
    - name: Configure poetry
      run: |
        python -m poetry config virtualenvs.in-project true

    - name: Cache the virtualenv
      uses: actions/cache@v2
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      run: |
        python -m poetry install

    - name: Run tests
      run: |
        python -m poetry run python -m pytest -sxv

    - name: Type checking
      run: |
        python -m poetry run python -m mypy .

    - name: Build packages
      run: |
        python -m poetry build
