name: Python CI

on:
  push:
    branches:
      - feat/modernization  
  pull_request:
    branches:
      - main 

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache Poetry
      uses: actions/cache@v2
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

  setup-python:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

  install-poetry:
    runs-on: ubuntu-latest
    needs: [cache]
    steps:
    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        source $HOME/.poetry/env

  install-dependencies:
    runs-on: ubuntu-latest
    needs: [setup-python, install-poetry]
    steps:
    - name: Install dependencies
      run: poetry install

  run-tests:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
    - name: Run tests
      run: poetry run pytest

  type-checking:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
    - name: Type checking
      run: poetry run mypy .

  build-packages:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
    - name: Build packages
      run: poetry build